### ISSUE TITLE
How do we build the compiler and use it

### ISSUE THREAD

**Issue by antonizoon** [BambooL/Natural-Expression#1]
Just tell me the instructions, and I'll put together a tutorial for developers to work with it. I kind of need it.

**Comment by BambooL** [comment]
Sure, I updated the Syntax part in README with examples. Can you refer to that? Please let me know if any misleadings.

**Comment by antonizoon** [comment]
That helps, but I need to know how to actually create and use the compiler on a `.let` program.

I assume you do this?

`python compiler.py test.let`

**Comment by BambooL** [comment]
Absolutely. Pull an updated version and try `python compiler.py let/torrent.let`.  To create such source code, you can store your code in Natural Expression in plain text with .let extension and currently, all the demos are in the let/let/ repository.

**Comment by antonizoon** [comment]
Thanks for the explanation. I'll add it to the README and try it out.

**Comment by antonizoon** [comment]
Updated Readme.md [with compilation instructions.](https://github.com/BambooL/Natural-Expression/commit/bce7c554415f7176f0ca9e4c02bfbb5e8d2099ff#diff-04c6e90faac2675aa89e2176d2eec7d8)

I also [proofread it a bit.](https://github.com/BambooL/Natural-Expression/commit/c619471c08a3bfe95e259757872abdf2c6bc49d0#diff-04c6e90faac2675aa89e2176d2eec7d8)
